### ISSUE TITLE
retard

### ISSUE THREAD

**Issue by 7x9z** [pathywathy/path#1]
nice dh script that logs ips for security meaures 🤓 and you keep ur user ids in plain text 💀💀💀
![image2](https://github.com/pathywathy/path/assets/48805031/32d2e29a-1886-48ef-8869-3c91dd0284ee)
![image](https://github.com/pathywathy/path/assets/48805031/ce4784d3-50c9-42bf-80db-0cba189f24ec)

**Comment by pathywathy** [comment]
this was when i had 1/2 months of experience in coding, ip only revealed to me if the user wasnt whitelisted, i dont log anymore 😭 
and this script has discontinued lmao

> nice dh script that logs ips for security meaures 🤓 and you keep ur user ids in plain text 💀💀💀 ![image2](https://private-user-images.githubusercontent.com/48805031/263380689-32d2e29a-1886-48ef-8869-3c91dd0284ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTUzOTUsIm5iZiI6MTcwMzExNTA5NSwicGF0aCI6Ii80ODgwNTAzMS8yNjMzODA2ODktMzJkMmUyOWEtMTg4Ni00OGVmLTg4NjktM2M5MWRkMDI4NGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIzMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3MTAwYWVhZWQ0NzdlN2QyOTk5MTE1MWQ3YmFmZDBlMmMyYTAxMzk0Y2MzNDYxOGI4ODU2OGFjMzBjYzkwNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oNQIAeuPo6tbjGxCEkncwuN3wQotiNKn-mQVCUc3PQA) ![image](https://private-user-images.githubusercontent.com/48805031/263380692-ce4784d3-50c9-42bf-80db-0cba189f24ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMTUzOTUsIm5iZiI6MTcwMzExNTA5NSwicGF0aCI6Ii80ODgwNTAzMS8yNjMzODA2OTItY2U0Nzg0ZDMtNTBjOS00MmJmLTgwZGItMGNiYTE4OWYyNGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDIzMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTZiZjc2YjMzMmNiMzAxNTJiYWNlMmFkN2ZiZmU2YzQ0OGFjZjg3MmM5ZWUwNDZjNmQzODc0NWVkZGM4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c3cvg6xIGbKOZyxMWNoHe72iCAhubI9BnwV3s3mo7mY)
